### PR TITLE
R gedi usage

### PR DESCRIPTION
**Pull request by grallewellyn**
Added example for submitting jobs with R
Used GEDI subsetter for an example https://docs.maap-project.org/en/latest/science/GEDI/GEDI_L4A.html#Submit-a-Job 

Since we have the following tickets for documenting with R:
For R Documentation, we have the following tickets:
[Cloud Optimized Access in Python and R](https://github.com/NASA-IMPACT/active-maap-sprint/issues/445) (Nathan Z)
[Accessing MAAP Data in R (AWS)](https://github.com/NASA-IMPACT/active-maap-sprint/issues/283) (Sheyenne)
[Accessing NASA CMR Data in R](https://github.com/NASA-IMPACT/active-maap-sprint/issues/1041) (Harshini/Sheyenne)
[MAAP STAC in R](https://github.com/NASA-IMPACT/active-maap-sprint/issues/1040) (Harshini/Sheyenne)
We have a couple more R tickets mainly revolving around GEDI data and DPS:
[Submitting DPS Jobs in R](https://github.com/NASA-IMPACT/active-maap-sprint/issues/1049)
[Access GEDI Granules Directly in R](https://github.com/NASA-IMPACT/active-maap-sprint/issues/1050)

I think it would be best to make a separate section for working with R like I did in this PR

### CODE REVIEW

**Comment by grallewellyn** [comment]
@wildintellect Made the suggested changes

**Comment by smk0033** [comment]
Thanks so much, Grace! I think it looks great. My only suggestion is formatting - I'd only update it to format it similar to our other docs for consistency (Author, Date, Description, Run This Notebook, and potentially Additional Resources if there was anything else you wanted to link to).

Also thank you for making another section for R notebooks - I'll be sure to add our R docs there!

**Review by smk0033 — CHANGES_REQUESTED** [review]
See comment (just formatting updates)

**Comment by grallewellyn** [comment]
Yes, I agree! Just updated

**Review by smk0033 — APPROVED** [review]
Looks good!

**Pull request merged**
