### PR TITLE
Merging Tutorials posted at Develop to Master

### PR DESCRIPTION
**Pull request by sumantjha**
Merging tutorial folders with currently posted GEDI and HLS tutorials to master.

### CODE REVIEW

**Comment by wildintellect** [comment]
@sumantjha now I recall this PR, I was suggesting @spa0002 should be the reviewer.

Review:
- [ ] Content renders correctly on https://docs.maap-project.org/en/develop/
- [ ] Verify content applies to the version of MAAP that users have access to.

**Comment by wildintellect** [comment]
- [ ] GEDI L2B lacks subheadings (minor) should not be a blocker.
- [ ] HLS tutorial is lacking screenshots/visualizations

Do we consider these blockers, or should we simply open tickets to address these, but go ahead with the PR?

**Comment by sumantjha** [comment]
I can address these before we review it again.

**Review by spa0002 — COMMENTED** [review]
Content renders correctly on https://docs.maap-project.org/en/develop/

@wildintellect What is meant by "version of MAAP that users have access to" in this case?

**Comment by spa0002** [comment]
When running HLS_search.ipynb and Search_GEDI.ipynb on ade.ops.maap-project.org, I receive the following error:
Screenshot 2022-11-22 at 1 24 45 PM

**Comment by spa0002** [comment]
When running GEDI_L4A_Example.ipynb on ade.ops.maap-project.org, there is a similar issue where geopandas is not found.
I receive the following error for the first code block in the 'Generate contour lines" section:
Screenshot 2022-11-22 at 1 47 40 PM

**Comment by anisbhsl** [comment]
> When running HLS_search.ipynb and Search_GEDI.ipynb on ade.ops.maap-project.org, I receive the following error: Screenshot 2022-11-22 at 1 24 45 PM

@spa0002 You need to install `geopandas` in your environment.

**Comment by spa0002** [comment]
> > When running HLS_search.ipynb and Search_GEDI.ipynb on ade.ops.maap-project.org, I receive the following error: Screenshot 2022-11-22 at 1 24 45 PM
> 
> @spa0002 You need to install `geopandas` in your environment.
Should we include a code block to demonstrate installing it in the environment?

**Comment by sumantjha** [comment]
> The reason I haven't added any command there is to make the notebook independent of pkg managers. This was mentioned by Chuck in his review of my PR.

@spa0002 @chuckwondo @wildintellect  is it acceptable to start adding a "requirement.txt" with each tutorial for a user to run before running any tutorial? Might help with removing the errors @spa0002 mentioned and not having to install missing packages in midst of running the notebook.

**Comment by wildintellect** [comment]
I think we need to discuss the approach at the next Architecture meeting (pip vs conda, code or just a list, etc...). If the requirements are stated at the top of the notebook that should not block this PR. TODO: enhancement - resolve how to best to inform and guide users to installing the correct requirements.

**Comment by wildintellect** [comment]
@sumantjha @anisbhsl in a meeting we agreed to list he python libraries at the top of each notebook, in a block that can be copied/pasted for use with `conda` or `pip`. Is someone working on that change?

**Comment by sumantjha** [comment]
I will do it. It is a small change.

**Review by spa0002 — APPROVED** [review]

**Comment by spa0002** [comment]
> * [ ]  GEDI L2B lacks subheadings (minor) should not be a blocker.
> * [x]  HLS tutorial is lacking screenshots/visualizations
> 
> Do we consider these blockers, or should we simply open tickets to address these, but go ahead with the PR?

https://docs.maap-project.org/en/latest/tutorials/HLS/HLS_search.html

**Comment by sumantjha** [comment]
The code is all pythonic and is not interacting with any external component. So, what screenshots are we looking for exactly in the above? 
That said, I do not think it is a blocker but an enhancement request which can be done in its own ticket.

**Pull request merged**
