### PR TITLE
Mlucas/jobs UI copy code

### PR DESCRIPTION
**Pull request by marjo-luc**

### CODE REVIEW

**Review by rtapella — APPROVED** [review]
it works!


could probably use some built-in help or other indication of what that button does...

**Comment by rtapella** [comment]
hm in develop maap-documentation this should be in
`/system_reference_guide/ade_custom_extensions/jobsui.html`

**Comment by rtapella** [comment]
oh this is just the docs 😆

**Comment by wildintellect** [comment]
@marjo-luc @rtapella this didn't get merged and now has a merge conflict, who wants to resolve so we can merge?

**Comment by rtapella** [comment]
working...

**Comment by rtapella** [comment]
I am re-building this in a new PR: https://github.com/MAAP-Project/maap-documentation/pull/266

**Comment by rtapella** [comment]
I think one issue with this old branch is that it doesn't reflect the doc re-org for some reason...

**Pull request closed without merging**
