### PR TITLE
Documentation for Data Request Issue Form

### PR DESCRIPTION
**Pull request by smk0033**
Issue/ticket: https://github.com/NASA-IMPACT/active-maap-sprint/issues/724

Updated issue form: https://github.com/MAAP-Project/Community/blob/master/.github/ISSUE_TEMPLATE/data_request.yaml

Creating a notebook for the Docs site to show users how to request new datasets using the updated issue form.

### CODE REVIEW

**Comment by smk0033** [comment]
I think this will close out the last open ticket for Objective 4 once this gets approved

**Review by omshinde — APPROVED** [review]
Looks good to me. The notebook explains all the details required to submit a data request. Thanks for your contributions.

**Review by jjfrench — APPROVED** [review]
I think this looks fine 👍🏼

**Comment by smk0033** [comment]
Thanks, y'all!

**Pull request merged**
