### PR TITLE
NISAR Notebook updates

### PR DESCRIPTION
**Pull request by smk0033**
Applying notebook updates per feedback from Sam

Github board ticket: https://github.com/NASA-IMPACT/active-maap-sprint/issues/979

### CODE REVIEW

**Comment by smk0033** [comment]
@nemo794 if you have a chance to look it over, here's the NISAR notebook with an updated visualization!

**Review by nemo794 — CHANGES_REQUESTED** [review]
Thank you, @smk0033 for putting this together! NISAR is not an easy dataset to work with, and despite the enormous number of comments, this notebook truly is a great starting point. :)

Some of my comments likely merit more discussion by the team to decide which direction to go. Once those directions are determined, then it'll be great to see where the dust settles after the adjustments are made.

Also, I submitted comments via ReviewNB, which is my first time using that. If that doesn't work... then please accept my apologies, and let's figure out a new method!

Thank you again!

**Comment by wildintellect** [comment]
<p>Mostly true - </p><ul><li>We did catalog the sample data in STAC</li><li>We did NOT make a copy, this example uses directly from the ASF hosted sample data.</li></ul>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644945'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>STAC does have a versioning extension which we could enable. I agree not critical to this demo currently, let's address that when a new version comes out.</p><p> </p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644966'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Interesting, I think the problem here is we are picking the item by numeric index, when we should actually filter the results based on the name of the product to be reliable.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645011'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>I disagree, for the NISAR data access the code differs from standard use of earthaccess because the ASF NISAR endpoint isn't standard.</p><p> </p><p>Also this method does technically work on MAAP, however it's really targetted at our users on VEDA where maap-py likely won't work.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645075'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Can you link to docs where is CF-1.7 is mentioned?</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645106'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p><code>from datatree import open_datatree</code></p><p>  You probably missed it because it wasn't changed in this diff it's hidden behind an expand button.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645126'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Do we want to say why we are applying a gamma correction?</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645174'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Future version, probably with Dask that would handle the tiling automatically.</p><p>So this sample file is not the same size an an expected real granule?</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645221'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by hrodmn** [comment]
<p>It is a little confusing how the S3 link is unrelated to the STAC item, this is one way you could show how to get it from the <code>search</code>:</p><p> </p><p><code></code><code></p><p>for item in client.search(collections="nisar-sim").items():</p><p>&nbsp;&nbsp;if asset := item.assets.get("GCOV"):</p><p>&nbsp;&nbsp;&nbsp;&nbsp;s3_link = asset.extra_fields["alternate"]["href"]</p><p>&nbsp;&nbsp;&nbsp;&nbsp;break</p><p></code><code></code></p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644987'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by hrodmn** [comment]
<p>It is tricky because each STAC item has a different asset!</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644987'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by hrodmn — COMMENTED** [review]
Nice work @smk0033! I added a few ideas on how to keep using the `datatree` instead of re-reading the file with `xr.open_dataset` and how to pull `s3_link` from the STAC search.

**Comment by wildintellect** [comment]
> It is a little confusing how the S3 link is unrelated to the STAC item, this is one way you could show how to get it from the `search`:
> 
> `for item in client.search(collections="nisar-sim").items():`
> 
> `  if asset := item.assets.get("GCOV"):`
> 
> `    s3_link = asset.extra_fields["alternate"]["href"]`
> 
> `    break`
> 
> [View entire conversation](https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644987) on ReviewNB

I think this is something we should fix on the STAC side. It's a little odd because the collection contains 1 item per asset type, and the id is the file name. I wonder if we should have done 1 item with 7 assets instead, or if we just need the Product to be more clear in the id or another metadata property so that you could sort them. cc: @jjfrench  

Note: In the real final product these might all be different collections.
Thoughts @nemo794 ?

**Comment by smk0033** [comment]
<p>Thank you so much, Henry! I was trying to get it to automate instead of hardcoding it, but the way I was trying it I kept getting errors and couldn't quite figure out how to get to that alternate href</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305644987'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
Thank you all for the great feedback! I'll work on incorporating it into the notebook and re-request reviews once ready

**Comment by smk0033** [comment]
<p>Good point! It looks like the method in the link provided focuses on accessing through CMR and then downloading the data. I agree we should probably work on that documentation to make it more comprehensive - taking note of that now!</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645056'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
Went ahead and requested reviews, I think I've address most of the comments about adjusting the contents of the notebook (I'll have to explore options pertaining to Alex's comment in the last cell still)

**Comment by wildintellect** [comment]
<p>I think I know how to clarify this even more. Our instructions MAAP or earthaccess are for direct access on AWS be it MAAP/VEDA or a users own cloud instances.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645056'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>it's not a default at all, I would have actually kept it all in UTM and just noted to the user how to see the data projection and change it if it was necessary.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645197'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>That indicates in the next version we should show how to spatially subset with Xarray. I'm a little worried that the reading ship sailed with use of Datatree which seemed to load a lot into memory. We'll need to research this more for the next version.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645221'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>Gotcha! I included it because I think changing it to lat/lon was brought up in our original meeting a little while back, but I don't remember the reasoning behind it. I could also be remembering wrong</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2364758488'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
@wildintellect addressed the additional comments you left!

**Comment by wildintellect** [comment]
<p>TBD if this matters or not.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/421/discussion/#comment-2305645106'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
