### PR TITLE
DPS tutorial updates 4.1.0

### PR DESCRIPTION
**Pull request by rtapella**

### CODE REVIEW

**Comment by rtapella** [comment]
hm let me fix the conflicts

**Comment by grallewellyn** [comment]
Why do we want to remove the section specifically for persistent storage? I know we repeat that information in "MAAP Storage Options" but wouldn't it be convenient to also have that information in FAQ?

**Comment by rtapella** [comment]
I think it was out of date so I figured it's easier to just maintain it all in one place.
It seems more like a section in the System Reference Guide that should be pointed at by other documents, rather than in the GS guide or a FAQs.

**Comment by grallewellyn** [comment]
Yes, I agree it is getting too chaotic to repeat information in multiple places

**Review by grallewellyn — APPROVED** [review]
Looks good to me

**Pull request merged**
