### PR TITLE
chore: missing datestamp

### PR DESCRIPTION
**Pull request by wildintellect**
we forgot to put the edit date on the document

### CODE REVIEW

**Review by jjfrench — APPROVED** [review]
ope, thanks!

**Review by smk0033 — APPROVED** [review]
Looks like a comma was also put in right after September. Looks good besides that - thanks for adding it!

**Comment by wildintellect** [comment]
@smk0033 removed the extra comma, please re-review

**Review by smk0033 — APPROVED** [review]
👍

**Pull request merged**
