### PR TITLE
Fix blurry image

### PR DESCRIPTION
**Pull request by grallewellyn**
Renamed image to import_granules_1

### CODE REVIEW

**Review by rtapella — COMMENTED** [review]
hm the import granules image change-diff says:
"File renamed without changes"

**Comment by rtapella** [comment]
also it doesn't seem to blurry to me..

**Comment by grallewellyn** [comment]
Strange, it looks fine here too: https://docs.maap-project.org/en/latest/system_reference_guide/faq/import_granules.html
Maybe we just close this PR then?

**Comment by rtapella** [comment]
sounds good to me... maybe I added the better image in with develop separately and now it looks like it wasn't updated. I have a vague memory of just copying your updated image in to a different branch...

**Pull request closed without merging**
