### PR TITLE
MAAP onboarding guide (#60)

### PR DESCRIPTION
**Pull request by spa0002**
* Getting started doc

### CODE REVIEW

**Comment by gchang** [comment]
@bsatoriu @spa0002 Viewing it in Github shows the correct screenshots, but in readthedocs, it's repeating the same SSH screen. Do the docs need to be rebuilt?

https://docs.maap-project.org/en/latest/getting_started.html
https://github.com/MAAP-Project/maap-documentation/blob/master/docs/source/getting_started.ipynb

**Comment by bsatoriu** [comment]
@gchang I noticed I had used the same alt text label for all the images. I just updated them to unique names in hopes that solves the repeating image issue. 

@spa0002 I committed this update to the develop branch: https://github.com/MAAP-Project/maap-documentation/commit/1f5dca803b2f9757b1782c97d9f6130b819729cc

**Comment by spa0002** [comment]
That was it. I built the "develop" version of the site and images appear correctly now.

https://docs.maap-project.org/en/develop/getting_started.html

Now can merge develop branch into master branch and build the "latest" version of the site to show changes on https://docs.maap-project.org/en/latest/

**Comment by bsatoriu** [comment]
Thanks. I was just able to confirm locally by installing the Sphinx tooling and building on my machine. I'll merge into master now.

**Pull request merged**
