### PR TITLE
chore: Update Visualizing MosaicJSON tutorial

### PR DESCRIPTION
**Pull request by jjfrench**
This is technically for "updating" the ade_mosaic tutorial. It seemed like a duplicate of the SRTM tutorial because they were both creating/displaying MosaicJSONs. The ade_mosaic tutorial was using ipycmc and generating the mosaics from a list of urls, I add the "generating mosaics from a list of urls" bit into the SRTM tutorial and renamed it in the codebase (shown tutorial name is still the same). The ade_mosaic was also applying a colormap to the request so I added that in as well.

### CODE REVIEW

**Review by smk0033 — APPROVED** [review]
👍🏻

**Comment by jjfrench** [comment]
<p>local "bucket" paths?</p><p> </p><p>It also is referencing the files within the ADE</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/314/discussion/#comment-1701916568'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
<p>Yes, I'm trying to clarify that in order for the Mosaic to work via Titiler the files must have an S3 path. This is only true for files in a private-bucket, my-public-bukcet, or shared-buckets path locally.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/314/discussion/#comment-1701916568'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jjfrench** [comment]
<p>Does the wording above resolve this? Or I could explicitly state "local private-bucket, my-public-bucket, or shared-buckets paths to their respective AWS S3 prefixes..."</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/314/discussion/#comment-1701916568'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wildintellect** [comment]
@jjfrench Let's ask someone less familiar with how this works to try it.

**Comment by wildintellect** [comment]
Sorry the changes look good but then I realized we're not making use of `pystac_client`

**Comment by jjfrench** [comment]
<p>we should, didn't see this - lint made the changes</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/314/discussion/#comment-1710681304'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jjfrench** [comment]
<p>I had tested using ipyleaflet but it seems to update the map instance in previous cells whereas folium doesn't</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/314/discussion/#comment-1710681321'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by wildintellect — APPROVED** [review]
Good enough for now, we can revisit the stac_ipyleaflet later.

**Pull request merged**
