### PR TITLE
srtm stac fixes

### PR DESCRIPTION
**Pull request by smk0033**
(Sorry, this should be under this PR but git was being weird: https://github.com/MAAP-Project/maap-documentation/pull/253)

Reference ticket: https://github.com/MAAP-Project/maap-documentation/issues/237

Tutorial got moved to STAC, updated the endpoint and made minor adjustments.

### CODE REVIEW

**Comment by smk0033** [comment]
<p>Hmm, I'm not sure why it's coming up that way, when I edit the notebook there isn't an extra space</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021461'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>VEDA also has a section labeled "Approach" that they do in some of theirs. Maybe we could do that instead of "About the Data"? I think Brian and I decided to leave "approach" out of the science tutorials though since we had the brief description and you're walked through the steps throughout the tutorial. Switching up the additional resources would make sense too, so I can look for more about visualization.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021488'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>They look so small here, I think I used ### for the markdown size, but I can up them to ## like the other headers</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021520'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>Oh wait, I see the extra space in the title, I thought the extra space was still showing up in the text that is hyperlinked. I'll change that! I think we could remove SRTM since it's in the description and will help shorten the title. </p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021461'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>Apparently the titles are showing up funky for some reason, this is already at ## heading size</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021520'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
@freitagb thoughts on Technical Tutorial guidelines? I included an "About the Data" section, but Jamison and I wonder if this can be left out? I know VEDA also has the option of doing an "Approach" section, but I think we decided to leave this out of the science tutorials since there is a brief description, and you're walked through the steps throughout the tutorial.

**Comment by freitagb** [comment]
<p>I think if we have reference to the SRTM dataset in the notebook, there should be some clarification within the notebook that it's not the authoritative data distributed by USGS, but transformed COGs within the MAAP STAC catalog. I agree that we can probably remove it from the top matter altogether if the purpose of the json is purely about visualizing a dataset within the MAAP STAC catalog.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1635021488'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by smk0033** [comment]
<p>I like something along the lines of that, definitely a little more descriptive!</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/261/discussion/#comment-1640702738'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jjfrench** [comment]
Oh sorry, my comment wasn't very clear - 
I think 
```
### Requirements

To be able to run this notebook you'll need the following requirements:

- rasterio
- folium
- requests
- tqdm
- rio-tiler (2.0b8) (Optional)
- cogeo-mosaic (Optional)
```

Is fine, we just don't need the `pip install` statements at the bottom of the markdown cell. Either way seems fine though!

**Comment by smk0033** [comment]
Gotcha! I just removed it all since they're in the code cell now, but I'll put that little section back! 🙂

**Pull request merged**
