### PR TITLE
Fix build configuration that broke

### PR DESCRIPTION
**Pull request by wildintellect**
Solving #186 
Not really sure why it broke, something in the underlying image ReadTheDocs was using might have changed.

Updated to use .readthedocs.yml which overrides some Advanced Settings in the web interface.
Also bumped the python version to 3.11 from 3.7 and versions of several packages.

This fix will need to be backported to all active branches before new PRs can be accepted or branches built. Starting with #184 that's currently broken.

### CODE REVIEW

**Comment by grallewellyn** [comment]
I am able to successfully run 
```
cd docs
make html
cd build/html
python3 -m http.server
```
and see the version of read the docs before we made the changes to getting started. 
But I am not sure if this problem was for local builds too

**Comment by rtapella** [comment]
> I am able to successfully run
> 
> ```
> cd docs
> make html
> cd build/html
> python3 -m http.server
> ```
> 
> and see the version of read the docs before we made the changes to getting started. But I am not sure if this problem was for local builds too

Local builds were working for me, too, but the CI was (is) not.

**Comment by wildintellect** [comment]
To be clear only ReadTheDoc builds were impacted, but it's good that these changes did not break your local (although for true test you probably would need to reinstall python libs from the requirements into a fresh environment)

**Comment by grallewellyn** [comment]
I tested with a fresh environment created by the current requirements.txt and that worked

**Review by rtapella — APPROVED** [review]
The fix works!

**Pull request merged**
