### PR TITLE
Added tutorial for GEDI02_A data, updated tutorials.rst

### PR DESCRIPTION
**Pull request by spa0002**
- Added tutorial for working with GEDI02_A data
- Updated tutorials.rst

### CODE REVIEW

**Comment by spa0002** [comment]
<p>I'm not sure I understand this comment.</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/152/discussion/#comment-1448963600'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by spa0002** [comment]
<p>granule UR perhaps? Reference: https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#g-granule-ur</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/152/discussion/#comment-1448963759'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sumantjha** [comment]
<p>Title case for words starting a comment, throughout the notebook. That was my intention. However, it is not necessary and varies from person to person. Feel free to ignore it. </p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/152/discussion/#comment-1448963600'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sumantjha** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/152/discussion/#comment-1448963759'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by spa0002** [comment]
@sumantjha Does this PR look like it's ready to merge into `develop`?

**Review by sumantjha — APPROVED** [review]
It looks good to me.

**Pull request merged**
